WebApp/WebApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentAssertions.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly WebAppContext _context;


        public BooksController(WebAppContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            return View(await _context.Book.ToListAsync());
        }


       

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(String Author,String Title, DateTime ReleaseDate,String Genre,int Price,String Adress, String email , String password)
        {

            Book book = new Book(Author, Title, Adress, ReleaseDate, Genre, Price);

            if (ModelState.IsValid && _context.User.Any(user => user.Email == email && user.Password == password ))
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Author,Title,ReleaseDate,Genre,Price")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        /*/ GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            _context.Book.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }*/


        // Authontification
        [HttpPost]
        public async Task<IActionResult> Auth( String email , String password)
        {

            User user = _context.User.Single(u => u.Email.ToLower() == email.ToLower() && u.Password == password);

            if (user != null)
            {               
                Session["user"] = user.Email.ToString();
               
                return RedirectToAction(nameof(Profile));
            }

            return RedirectToAction(nameof(Index));

        }

        //profile
        public async Task<IActionResult> Profile()
        {
            if(Session["user"] != null)
             {
                 User user = (User)(Session["user"]);

                 return View(user);
             }
           
            return View();
        }

        // sign up
        public async Task<IActionResult> Deconnect()
        {
            Session.Remove["user"];

            return RedirectToAction(nameof(Profile));
        }
        // searsh
        public async Task<IActionResult> FindBook(String searsh)
        {
            return View(await _context.Book.Where(m => (m.Author + m.Title + m.Genre).ToLower().Contains(searsh.ToLower()) || searsh == null).ToListAsync());
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.Id == id);
        }

        private bool PanierTitleExists(String title)
        {
            return _context.Panier.Any(e => e.Title == title);
        }


        //+++++++++++++++++++++++  Panier  +++++++++++++++++++++++++++++++++++++++++

        // GET: Paniers
        public async Task<IActionResult> PanierIndex()
        {
            return View(await _context.Panier.ToListAsync());
        }

        // GET: Paniers/Details/5
        public async Task<IActionResult> PanierDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }


        // GET: Paniers/Create
        public async Task<IActionResult> AddPanier(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Book.FindAsync(id);
            Panier panier1 = new Panier(panier.Author, panier.Title, panier.Adress, panier.ReleaseDate, panier.Genre, panier.Price);
            if (panier1 == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (PanierTitleExists(panier.Title))
                {
                    return RedirectToAction(nameof(Index));
                }
                _context.Add(panier1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }          
            return RedirectToAction(nameof(Index));
            
        }


        // GET: Paniers/Delete/5
        public async Task<IActionResult> PanierDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panier = await _context.Panier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }

        // POST: Paniers/Delete/5
        [HttpPost, ActionName("PanierDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PanierDeleteConfirmed(int id)
        {
            var panier = await _context.Panier.FindAsync(id);
            _context.Panier.Remove(panier);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(PanierIndex));
        }

        



       
    }
}

WebApp/WebApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly WebAppContext _context;

        public UsersController(WebAppContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Last_Name,Phone,Email,Password,Type_User")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));

                return RedirectToAction("Index","");

            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Last_Name,Phone,Email,Password,Type_User")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
    }
}

WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

   
   
    <!-- ################################## tist ######################################### -->
    <link rel="apple-touch-icon" sizes="57x57" href="~/image_icon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/image_icon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/image_icon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/image_icon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/image_icon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/image_icon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/image_icon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/image_icon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/image_icon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/image_icon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/image_icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/image_icon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/image_icon/favicon-16x16.png">

    <link rel="manifest" href="~/css/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/image_icon/favicon-16x16.png">
    <meta name="theme-color" content="#ffffff">

    <link href='~/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <link href="~/css/new1.css" rel="stylesheet">
    <link href='~/css/bootstrap.min.css' rel='stylesheet' type='text/css'>
    <link href='~/css/bootstrap-social.css' rel='stylesheet' type='text/css'>
    <link href='~/css/new2.css' rel='stylesheet' type='text/css'>
    <link href="~/css/profile.css" rel="stylesheet" />


    <script src="~/css/jquery-3.2.1.min.js"></script>
    <script src="~/css/bootstrap.min.js"></script>
    <!-- ########################################################################### -->


</head>



<body>


    <div class="header">
        <div class="navbar navbar-blue" role="navigation">
            <div class="navbar-header">
                <a class="logo" asp-controller="Books" asp-action="Index">
                    <img src="~/image_icon/epdf_logo.png" style="max-height: 60px;" />
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-controller="Books" asp-action="Index"><i class="fa fa-home"></i> Home</a></li>
                    <li class="active"><a asp-controller="Books" asp-action="Profile"><i class="fa fa-home"></i>Profile</a></li>
                    <li class="active"><a asp-controller="Books" asp-action="PanierIndex"><i class="fa fa-home"></i>Panier</a></li>
                    <li class="active"><a asp-controller="Books" asp-action="Create"><i class="fa fa-home"></i> Add Document</a></li>
                    <li><a data-toggle="modal" data-target="#login"><i class="fa fa-sign-in"></i> Sign In</a></li>
                    
                </ul>
                <div class="search_box">

                    <!-- ########## Find Book ########### -->

                    <form method="post" action="/Books/FindBook" target="_top" >
                        <div class="form-group">
                            <div class="input-group input-group-lg">
                                <input type="text" class="form-control"  name="searsh" id="document_search" placeholder="Search Documents">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- ########################## -->
                </div>
            </div>
        </div>
    </div>


    <!-- #################################### Afich continue  ############################################# -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- ###################################################################################### -->



    <footer class="footer" style="margin-top: 60px;">
        <div class="container">
            &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- ************ *********** Modal **************************-->
    <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" on="tap:login.close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="add-note-label">Sign In</h4>
                </div>
                <div class="modal-body">

                    <!-- ********************************************************************************************************* -->

                    <form method="post" action="/Books/Auth">
                        <div class="form-group">
                            <label class="sr-only" for="email">Email</label>
                            <input class="form-input form-control" type="text" name="email" id="email" value="" placeholder="Email" />
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="password">Password</label>
                            <input class="form-input form-control" type="password" name="password" id="password" value="" placeholder="Password" />
                        </div>
                        <div class="form-group">
                            <div class="checkbox">
                                <label class="form-checkbox">
                                    <input type="checkbox" name="remember" value="1" />
                                    <i class="form-icon"></i> Remember me
                                </label>
                                <label class="pull-right"><a asp-controller="Users" asp-action="Create">Register</a></label>
                            </div>

                        </div>
                        <button class="btn btn-primary btn-block" type="submit">Sign In</button>
                    </form>


                    <!-- *************************************************************************************************************************** -->

                </div>
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)


</body>
</html>